// Create Ideas
export const POST_IDEA_START = 'POST_IDEA_START';
export const POST_IDEA_SUCCESS = 'POST_IDEA_SUCCESS';
export const POST_IDEA_FAILURE = 'POST_IDEA_FAILURE';

// Create Draft Ideas
export const DRAFT_IDEA_START = 'DRAFT_IDEA_START';
export const DRAFT_IDEA_SUCCESS = 'DRAFT_IDEA_SUCCESS';
export const DRAFT_IDEA_FAILURE = 'DRAFT_IDEA_FAILURE';

// get user infromation
export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

// get show idea page data
export const GET_IDEA_START = 'GET_IDEA_START';
export const GET_IDEA_SUCCESS = 'GET_IDEA_SUCCESS';
export const GET_IDEA_FAILURE = 'GET_IDEA_FAILURE';

// get all idea order by latest
export const GET_ALL_IDEA_LATEST_START = 'GET_ALL_IDEA_LATEST_START';
export const GET_ALL_IDEA_LATEST_SUCCESS = 'GET_ALL_IDEA_LATEST_SUCCESS';
export const GET_ALL_IDEA_LATEST_FAILURE = 'GET_ALL_IDEA_LATEST_FAILURE';

// get all idea order by good counnt
export const GET_ALL_IDEA_GOOD_START = 'GET_ALL_IDEA_GOOD_START';
export const GET_ALL_IDEA_GOOD_SUCCESS = 'GET_ALL_IDEA_GOOD_SUCCESS';
export const GET_ALL_IDEA_GOOD_FAILURE = 'GET_ALL_IDEA_GOOD_FAILURE';

// Create Comment for Idea
export const CREATE_COMMENT_START = 'CREATE_COMMENT_START';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

// get comment for idea
export const GET_COMMENT_START = 'GET_COMMENT_START';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAILURE = 'GET_COMMENT_FAILURE';

// idea good count change
export const GOOD_COUNT_CHANGE_START = 'GOOD_COUNT_CHANGE_START';
export const GOOD_COUNT_CHANGE_SUCCESS = 'GOOD_COUNT_CHANGE_SUCCESS';
export const GOOD_COUNT_CHANGE_FAILURE = 'GOOD_COUNT_CHANGE_FAILURE';

// user login
export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

// user already login check ALREADY
export const USER_ALREADY_LOGIN_START = 'USER_ALREADY_LOGIN_START';
export const USER_ALREADY_LOGIN_SUCCESS = 'USER_ALREADY_LOGIN_SUCCESS';
export const USER_ALREADY_LOGIN_FAILURE = 'USER_ALREADY_LOGIN_FAILURE';

// user logout
export const USER_LOGOUT_START = 'USER_LOGOUT_START';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';