// Create Ideas
export const POST_IDEA_START = 'POST_IDEA_START';
export const POST_IDEA_SUCCESS = 'POST_IDEA_SUCCESS';
export const POST_IDEA_FAILURE = 'POST_IDEA_FAILURE';

// Create Draft Ideas
export const DRAFT_IDEA_START = 'DRAFT_IDEA_START';
export const DRAFT_IDEA_SUCCESS = 'DRAFT_IDEA_SUCCESS';
export const DRAFT_IDEA_FAILURE = 'DRAFT_IDEA_FAILURE';

// get user infromation
export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

// get show idea page data
export const GET_IDEA_START = 'GET_IDEA_START';
export const GET_IDEA_SUCCESS = 'GET_IDEA_SUCCESS';
export const GET_IDEA_FAILURE = 'GET_IDEA_FAILURE';